// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenInternetRadio
void ui_ScreenInternetRadio_screen_init(void);
lv_obj_t * ui_ScreenInternetRadio;
lv_obj_t * ui_contButton;
lv_obj_t * ui_btnInternetRadio;
lv_obj_t * ui_lblInternetRadio;
lv_obj_t * ui_btnSD;
lv_obj_t * ui_lblSD;
lv_obj_t * ui_btnPhone;
lv_obj_t * ui_lblPhone;
void ui_event_rlrStation(lv_event_t * e);
lv_obj_t * ui_rlrStation;
lv_obj_t * ui_imageStation;


// SCREEN: ui_ScreenSaver
void ui_ScreenSaver_screen_init(void);
lv_obj_t * ui_ScreenSaver;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_rlrStation(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        playInternetRadio(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenInternetRadio_screen_init();
    ui_ScreenSaver_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenInternetRadio);
}
