// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_ScreenInternetRadio
void ui_ScreenInternetRadio_screen_init(void);
extern lv_obj_t * ui_ScreenInternetRadio;
extern lv_obj_t * ui_contButton;
extern lv_obj_t * ui_btnInternetRadio;
extern lv_obj_t * ui_lblInternetRadio;
extern lv_obj_t * ui_btnSD;
extern lv_obj_t * ui_lblSD;
extern lv_obj_t * ui_btnPhone;
extern lv_obj_t * ui_lblPhone;
void ui_event_rlrStation(lv_event_t * e);
extern lv_obj_t * ui_rlrStation;
extern lv_obj_t * ui_imageStation;
// SCREEN: ui_ScreenSaver
void ui_ScreenSaver_screen_init(void);
extern lv_obj_t * ui_ScreenSaver;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_579413331);    // assets\no-stations.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
