// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenInternetRadio_screen_init(void)
{
    ui_ScreenInternetRadio = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenInternetRadio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_contButton = lv_obj_create(ui_ScreenInternetRadio);
    lv_obj_remove_style_all(ui_contButton);
    lv_obj_set_width(ui_contButton, 128);
    lv_obj_set_height(ui_contButton, 384);
    lv_obj_set_x(ui_contButton, 48);
    lv_obj_set_y(ui_contButton, 0);
    lv_obj_set_align(ui_contButton, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_contButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnInternetRadio = lv_obj_create(ui_contButton);
    lv_obj_set_width(ui_btnInternetRadio, 128);
    lv_obj_set_height(ui_btnInternetRadio, 128);
    lv_obj_clear_flag(ui_btnInternetRadio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnInternetRadio, lv_color_hex(0x4DAAD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnInternetRadio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblInternetRadio = lv_label_create(ui_btnInternetRadio);
    lv_obj_set_width(ui_lblInternetRadio, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblInternetRadio, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblInternetRadio, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblInternetRadio, "Internet\nRadio");
    lv_obj_set_style_text_color(ui_lblInternetRadio, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblInternetRadio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblInternetRadio, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblInternetRadio, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSD = lv_obj_create(ui_contButton);
    lv_obj_set_width(ui_btnSD, 128);
    lv_obj_set_height(ui_btnSD, 128);
    lv_obj_set_align(ui_btnSD, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_btnSD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnSD, lv_color_hex(0x4DAAD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSD = lv_label_create(ui_btnSD);
    lv_obj_set_width(ui_lblSD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblSD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSD, "SD card");
    lv_obj_set_style_text_color(ui_lblSD, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblSD, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSD, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnPhone = lv_obj_create(ui_contButton);
    lv_obj_set_width(ui_btnPhone, 128);
    lv_obj_set_height(ui_btnPhone, 128);
    lv_obj_set_align(ui_btnPhone, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_btnPhone, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnPhone, lv_color_hex(0x4DAAD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnPhone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblPhone = lv_label_create(ui_btnPhone);
    lv_obj_set_width(ui_lblPhone, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPhone, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblPhone, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPhone, "Phone");
    lv_obj_set_style_text_color(ui_lblPhone, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblPhone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblPhone, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblPhone, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rlrStation = lv_roller_create(ui_ScreenInternetRadio);
    lv_roller_set_options(ui_rlrStation, "Station 1\nStation 2\nStation 3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_rlrStation, 530);
    lv_obj_set_height(ui_rlrStation, 128);
    lv_obj_set_x(ui_rlrStation, -48);
    lv_obj_set_y(ui_rlrStation, -48);
    lv_obj_set_align(ui_rlrStation, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_set_style_text_color(ui_rlrStation, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rlrStation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rlrStation, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rlrStation, lv_color_hex(0x2E6680), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rlrStation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_rlrStation, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rlrStation, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rlrStation, lv_color_hex(0x4DAAD4), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rlrStation, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_imageStation = lv_img_create(ui_ScreenInternetRadio);
    lv_img_set_src(ui_imageStation, &ui_img_579413331);
    lv_obj_set_width(ui_imageStation, 196);
    lv_obj_set_height(ui_imageStation, 196);
    lv_obj_set_x(ui_imageStation, -215);
    lv_obj_set_y(ui_imageStation, 48);
    lv_obj_set_align(ui_imageStation, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_imageStation, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imageStation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_rlrStation, ui_event_rlrStation, LV_EVENT_ALL, NULL);

}
